### ISSUE TITLE
Pressing the "Continue" button in the pause menu breaks the pause menu.

### ISSUE THREAD

**Issue by Derpford** [naelstrof/KoboldKare#29] opened 2022-01-09 10:12 UTC
What it says on the tin. Pressing ESC to close the menu works fine, but clicking "Continue" causes the menu to break; pressing ESC again pauses the game, but does not bring up the menu.

**Comment by Firgof** [comment] 2022-01-09 14:53
Replicated and bug found. Fix is being created presently. Thank you!

**Comment by Firgof** [comment] 2022-01-09 15:06
Alright, fix should be pushed to repo now. Pull at your leisure and lemme know if it resolved the issue on your end.

**Comment by Derpford** [comment] 2022-01-10 03:21
Good news: the continue button works now.

Bad news: It appears the "New Save" button in the save/load menu has the same problem.

**Comment by Firgof** [comment] 2022-01-10 15:56
Confirmed same issue, fix will be on-repo in a moment. Closing this issue due to it being resolved. Please feel free to submit more issues as they occur!

**Closed by Firgof** 2022-01-10 15:56 UTC
Labels: bug
